### ISSUE TITLE
Words in the functions names are not separated by underscores

### ISSUE THREAD

**Issue by ValeryiaLukyanava** [Zergoks/InternalEducation#1]
Words in the names of the functions are not separated by underscores, e.g.:
https://github.com/Zergoks/InternalEducation/blob/ed846a4d4b5a1f55c1dd9bd74ef6ae674633255a/conftest.py#L15

**Expected**:
Based on PEP 8 -- Style Guide for Python Code (https://www.python.org/dev/peps/pep-0008/#id45):
`pytest_add_option`

**Comment by Zergoks** [comment]
pytest cant recognize pytest_add_option function. So it must be pytest_addoption.
So fix reverted

**Comment by ValeryiaLukyanava** [comment]
Got it. So it's not your own method - closed.
