### ISSUE TITLE
FYI: You can use Faker for random string generation

### ISSUE THREAD

**Issue by ValeryiaLukyanava** [Zergoks/InternalEducation#12]
https://github.com/Zergoks/InternalEducation/blob/a800e1f3095545e0d1e90cacc09db9d45377a906/Core/utils.py#L11
Despite the fact that implementation is correct, in automated tests, this random string generation is usually carried out using libraries, such as `Faker`: https://faker.readthedocs.io/en/master/

**Comment by Zergoks** [comment]
Yea. Already experienced Faker in API tests. At this point, using Faker lib seems excessive because it is just one function, and it can be written with built-in functionality
