### ISSUE TITLE
Why does `raise` occur after `except`?

### ISSUE THREAD

**Issue by ValeryiaLukyanava** [Zergoks/InternalEducation#14]
Why does `raise` occur after `except`?
https://github.com/Zergoks/InternalEducation/blob/a800e1f3095545e0d1e90cacc09db9d45377a906/Core/driver_extension.py#L37

**Comment by Zergoks** [comment]
This method developed for taking screenshot in any moment. So the main point to log error and throw exception for debugging because in normal flow this should never happen. @ValeryiaLukyanava is it acceptable?

**Comment by ValeryiaLukyanava** [comment]
As you can see, Selenium's method `get_screenshot_as_file` (that is called from `save_screenshot()`) is safe:
![image](https://user-images.githubusercontent.com/78210745/123065987-5547bb00-d418-11eb-9a04-0603752579f0.png)
see also: https://www.selenium.dev/selenium/docs/api/py/_modules/selenium/webdriver/remote/webdriver.html
So you can not care about handling exceptions (can remove `try`..`except`..`raise`)

**Comment by Zergoks** [comment]
Good point. Many thanks. I will replace try..except with if..else for logging purposes

**Comment by ValeryiaLukyanava** [comment]
LGFM 👍
