### ISSUE TITLE
It is not good practice to `import *`

### ISSUE THREAD

**Issue by ValeryiaLukyanava** [Zergoks/InternalEducation#15]
https://github.com/Zergoks/InternalEducation/blob/a800e1f3095545e0d1e90cacc09db9d45377a906/Core/driver_extension.py#L8

**Comment by Zergoks** [comment]
Totally agree in general. But in this particular case when we know what exactly hidden under * problems with imported and local variables are unlikely.
@ValeryiaLukyanava Do you think it is better to explicitly import exception in this case also?

**Comment by ValeryiaLukyanava** [comment]
Yes, for sure. The exceptions that you are working with

**Comment by ValeryiaLukyanava** [comment]
LGFM :+1:
