### ISSUE TITLE
Using bare `except` is not good practice

### ISSUE THREAD

**Issue by ValeryiaLukyanava** [Zergoks/InternalEducation#22]
https://github.com/Zergoks/InternalEducation/blob/a800e1f3095545e0d1e90cacc09db9d45377a906/Core/driver_extension.py#L101
You can handle `JavascriptException` here:
![image](https://user-images.githubusercontent.com/78210745/123069075-1ff09c80-d41b-11eb-92bc-5a7c342693b9.png)
See also: https://www.selenium.dev/selenium/docs/api/py/_modules/selenium/webdriver/remote/webdriver.html

**Comment by Zergoks** [comment]
Many thanks!

**Comment by ValeryiaLukyanava** [comment]
LGFM :+1:
