### ISSUE TITLE
Incorrect usage of the asterisk with function arguments

### ISSUE THREAD

**Issue by ValeryiaLukyanava** [Zergoks/InternalEducation#3]
Incorrect usage of the asterisk (`*`) with function arguments:
https://github.com/Zergoks/InternalEducation/blob/ed846a4d4b5a1f55c1dd9bd74ef6ae674633255a/Pages/BasePage.py#L16

Expected: 
In Python we use `*` before the parameter name in the function definition if we do not know how many arguments will be passed into our function: https://docs.python.org/3/tutorial/controlflow.html#arbitrary-argument-lists
But working with Selenium Web Driver we usually know how many arguments we are going to pass.

**Comment by Zergoks** [comment]
According to PEP 0448 there is no restriction on the use of unpacking when calling a function: https://www.python.org/dev/peps/pep-0448/

But perhaps working with the element model inside the function will improve readability and be more "pytonic".

**Comment by ValeryiaLukyanava** [comment]
LGFM :+1:
